apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
  namespace: envoy-gateway-system
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: eg
  namespace: envoy-gateway-system
spec:
  gatewayClassName: eg
  infrastructure:
    annotations:
      metallb.io/loadBalancerIPs: 192.168.2.150
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: openwebrx-https
      protocol: HTTPS
      hostname: "openwebrx.homelab.larsmaes.nl"
      port: 444
      tls:
        mode: Terminate
        certificateRefs:
          - name: eg-tls-openwebrx
            kind: Secret
    - name: web-https
      protocol: HTTPS
      hostname: "web.homelab.larsmaes.nl"
      port: 444
      tls:
        mode: Terminate
        certificateRefs:
          - name: eg-tls-web
            kind: Secret