apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebrx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwebrx
  template:
    metadata:
      labels:
        app: openwebrx
    spec:
      containers:
      - name: openwebrx
        image: slechev/openwebrxplus-softmbe:latest
        ports:
        - containerPort: 8073
        imagePullPolicy: Always
        volumeMounts:
        - name: openwebrx-etcsettings
          mountPath: /etc/openwebrx
        - name: openwebrx-settings
          mountPath: /var/lib/openwebrx
        - name: openwebrx-plugins
          mountPath: /usr/lib/python3/dist-packages/htdocs/plugins
        - name: openwebrx-temp
          mountPath: /tmp
      volumes:
      - name: openwebrx-etcsettings
        persistentVolumeClaim:
          claimName: openwebrx-etc-pvc
      - name: openwebrx-settings
        persistentVolumeClaim:
          claimName: openwebrx-pvc
      - name: openwebrx-plugins
        persistentVolumeClaim:
          claimName: openwebrx-plugins-pvc
        # configMap:
        #   name: openwebrx-config-1
      - name: openwebrx-temp
        emptyDir:
          medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: openwebrx-service
spec:
  selector:
    app: openwebrx
  ports:
  - name: http
    port: 8073
    targetPort: 8073
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: openwebrx-ingress
#   annotations: 
#     cert-manager.io/cluster-issuer: letsencrypt-prod
# spec:  
#   rules:
#   - host: openwebrx.homelab.larsmaes.nl
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: openwebrx-service
#             port:
#               number: 8073
#   tls:
#     - hosts: 
#         - openwebrx.homelab.larsmaes.nl
#       secretName: tls-2024-openwebrx-homelab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebrx-etc-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebrx-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebrx-plugins-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openwebrx-httproute
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
  hostnames:
    - "openwebrx.homelab.larsmaes.nl"
  rules:
  - backendRefs:
    - name: openwebrx-service
      port: 8073